### ISSUE TITLE
TypeError: call.mapError is not a function

### ISSUE THREAD

**Issue by zherr** [Kentico/kontent-test-http-service-js#9]
### Brief bug description

While using the `KontentTestHttpService` to mock kentico management API calls, we encountered an error when mocking a bad request:
```typescript
const mockResponseConfig = new Map<RegExp, FakeResponseConfig>();
mockResponseConfig.set(/.*/, {
  errorJson: 'some error',
  throwError: true,
});

const mockKenticoHttpService = new KontentTestHttpService(mockResponseConfig);

const client = new ManagementClient({
  projectId: 'secret',
  apiKey: 'secret',
  httpService,
});

await client.
  .viewContentItem()
  .byItemCodename(codename)
  .toObservable()
  .toPromise();
```

And the error we receive is:
```
    TypeError: call.mapError is not a function
        at KontentTestHttpService.get (/Users/zacharyherr/Workspace/chat-admin/backend/node_modules/@kentico/kontent-test-http-service-js/src/kontent-test-http-service.ts:64:39)
```

### Repro steps

See above setup.

### Expected behavior

Library correctly mocks an invalid response without throwing an error from within the library.

### Test environment

 - Platform/OS: OSX
 - Browser: N/A
 - Version: 2.1.0

**Comment by Simply007** [comment]
Hey @zherr,

thanks for the issue. I have checked the repo and it looks like it covers Delivery Core JS package v 4.0.0.

I will check with my colleagues, but I guess this package could be deprecated and you could use `TestHttpService` right from "@kentico/kontent-core" (+ update Readme: https://github.com/Kentico/kontent-core-js#testing)

Example of Management Client tests https://github.com/Kentico/kontent-management-sdk-js/blob/master/test-browser/setup/cm-test-client.ts#L33-L42

Please let me know if the `TestHttpService` works for you.

**Comment by zherr** [comment]
Hey @Simply007 , thank you for such a swift response.

The `TestHttpService` from `@kentico/kontent-core` is working great now, for both mocking errors and successful requests.

We'll ditch this library for that one per your recommendation. Thanks for being vigilant and updating the documentation!
